# Use Node.js as base image
FROM node:22-alpine3.19 AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./nextjsapp1/package.json ./nextjsapp1/package-lock.json ./

# Install dependencies
RUN npm install
RUN npm audit fix --force

# Copy the rest of the application
COPY ./nextjsapp1 . 


RUN npm run build

# Stage 2: Serve the app with a lightweight Node.js image
FROM node:22-alpine3.19
# Set working directory
WORKDIR /app

# Copy the build output from the previous stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json .

# Expose port
EXPOSE 3000


# # Run the app
CMD ["npm", "start"]
