# Use the official golang image as base
FROM golang:1.17-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app



COPY ./go .

# Build the Go app
RUN go build -o helloworld .

# Start a new stage from scratch
FROM scratch

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/helloworld /app/helloworld

# Command to run the executable
CMD ["/app/helloworld"]
