name: Go Application CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['go/**']
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Run linter
        run: go vet ./...

  docker-build:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./go


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./go/DockerFile
          push: true
          tags: rahulupadhayay/helloworldgo:latest
